cart page
beyond-io/superx pull request #57
Opened 2020-10-16 04:29 UTC by aryehlev

alot of code was taken from @OdedHellman 's PR i just figured we should get it PR'd

2020-10-16 06:46 UTC, simzacks requested changes
remove the log file.
It says there are conflicts. Please pull and rebase and submit again

2020-10-17 06:55 UTC, shaibrown5 commented on superx/routes/home.py
> +                total_prices['victory']['price'] += same_item.price
you are doing the same thing in every if, the only thing that changes is the name of the super. mabe try this (easier on the eyes)

```
for same_item in price_list_of_item:
    super_name = ''
    
    if same_item.chain_id == sd['mega']['chain_id']:
        super_name = 'mega'
    elif same_item.chain_id == sd['shufersal']['chain_id']:
        super_name = 'shufersal'
    elif same_item.chain_id == sd['victory']['chain_id']:
        super_name = 'victory'

    total_prices[super_name]['list'].append({
        "name": item['name'],
        "price": same_item.price
    })
    total_prices[super_name]['price'] += same_item.price
```

2020-10-17 18:42 UTC, aryehlev commented on superx/routes/home.py
> +                total_prices['victory']['price'] += same_item.price
good point, done!

2020-10-17 18:43 UTC, aryehlev commented
ok i have updated it, there are no conflicts now

2020-10-18 05:24 UTC, shaibrown5 commented on superx/routes/home.py
> +                total_prices['victory']['price'] += same_item.price
dont forget to push the code

2020-10-18 09:07 UTC, OdedHellman commented
Nicely done @aryehlev... looks good!

2020-10-18 23:05 UTC, closed without merging